version: "3"
services:
  php:
    image: php:7-apache
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    links:
      - mysql
    command: "bash -c 'docker-php-ext-install mysqli && docker-php-ext-enable mysqli && apachectl restart && tail -f /dev/null'"
    command: "bash -c 'docker-php-ext-install mysqli && docker-php-ext-enable mysqli && docker-php-ext-install pdo pdo_mysql && apachectl restart && tail -f /dev/null'"
    
  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: mca
      MYSQL_PASSWORD: 12345
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8083:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
